; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
framework = arduino
lib_deps =
    m5stack/M5Unified @ ^0.2.2
    meganetaaan/M5Stack-Avatar @ ^0.10.0
    bblanchon/ArduinoJson @ ^7
    https://github.com/ESP32Async/ESPAsyncWebServer.git
    https://github.com/ESP32Async/AsyncTCP.git
monitor_speed = 921600

[env:m5stack-cores3]
board = m5stack-cores3
board_build.partitions = default_16MB.csv
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DENABLE_CAMERA
    -DBOARD_HAS_PSRAM

[env:m5stack-core]
board = m5stack-core-esp32
board_build.partitions = default.csv

[env:m5stack-core2]
board = m5stack-core2
board_build.partitions = default_16MB.csv
