#!/usr/bin/env bash
# Cross-platform setup for piper-plus TTS (default engine for stackchan-atama).
#
# Downloads the native piper-plus binary (with bundled OpenJTalk for Japanese),
# not the C# CLI variant. The native binary phonemizes Japanese with OpenJTalk
# which produces correct prosody; the C# CLI falls back to multilingual espeak
# phonemes which can sound non-native.
#
# Downloads:
#   - piper-plus native binary from ayutaz/piper-plus releases
#   - tsukuyomi-chan voice model from Hugging Face (ayousanz/piper-plus-tsukuyomi-chan)
# Installs into:
#   <skill>/_piper/    -- native binary + ORT runtime + OpenJTalk dict
#   <skill>/models/    -- model + config
#   <skill>/tools/piper -- shell wrapper (stdin -> -t conversion)
#
# Usage:
#   tools/setup_piper.sh                  # auto-detect OS/ARCH
#   PIPER_PLUS_VERSION=v1.11.0 tools/setup_piper.sh
#   FORCE=1 tools/setup_piper.sh          # re-download even if installed

set -euo pipefail

PIPER_PLUS_VERSION="${PIPER_PLUS_VERSION:-v1.11.0}"
MODEL_REPO="ayousanz/piper-plus-tsukuyomi-chan"
MODEL_FILE="tsukuyomi-chan-6lang-fp16.onnx"

SKILL_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PIPER_DIR="$SKILL_DIR/_piper"
MODELS_DIR="$SKILL_DIR/models"
WRAPPER="$SKILL_DIR/tools/piper"

log() { printf '[setup_piper] %s\n' "$*"; }
err() { printf '[setup_piper] ERROR: %s\n' "$*" >&2; exit 1; }

# ---- Detect platform ----
OS="$(uname -s)"
ARCH="$(uname -m)"

case "$OS-$ARCH" in
    Darwin-arm64)  ASSET="piper-macos-arm64.tar.gz" ;;
    Linux-aarch64|Linux-arm64)
                   ASSET="piper-linux-arm64.tar.gz" ;;
    Linux-armv7l|Linux-armv6l)
                   ASSET="piper-linux-armv7.tar.gz" ;;
    Linux-x86_64)  ASSET="piper-linux-x64.tar.gz" ;;
    Darwin-x86_64)
        err "macOS Intel (x86_64) is not supported by native piper-plus (only macOS arm64). Use Linux or arm64 Mac." ;;
    *) err "unsupported platform: $OS-$ARCH" ;;
esac

log "platform: $OS-$ARCH -> $ASSET"

# ---- Tools ----
have() { command -v "$1" >/dev/null 2>&1; }
have curl || err "curl is required"
have tar  || err "tar is required"

# ---- Install piper-plus native binary ----
mkdir -p "$PIPER_DIR" "$MODELS_DIR"
PIPER_BIN="$PIPER_DIR/piper/bin/piper"

if [ "${FORCE:-0}" = "1" ] || [ ! -x "$PIPER_BIN" ]; then
    log "downloading $ASSET ($PIPER_PLUS_VERSION) ..."
    URL="https://github.com/ayutaz/piper-plus/releases/download/$PIPER_PLUS_VERSION/$ASSET"
    TMP="$(mktemp -d)"
    trap 'rm -rf "$TMP"' EXIT
    curl -fL --progress-bar -o "$TMP/asset.tar.gz" "$URL"
    # Tarball top-level is "piper/" — extract preserving that so we get _piper/piper/bin/piper
    rm -rf "$PIPER_DIR/piper"
    tar xzf "$TMP/asset.tar.gz" -C "$PIPER_DIR"
    log "extracted to $PIPER_DIR/piper"

    # Strip macOS quarantine attribute so the binary can run without Gatekeeper prompts
    if [ "$OS" = "Darwin" ] && have xattr; then
        xattr -dr com.apple.quarantine "$PIPER_DIR" 2>/dev/null || true
    fi

    chmod +x "$PIPER_BIN" 2>/dev/null || true
else
    log "piper binary already installed (use FORCE=1 to re-download)"
fi

[ -x "$PIPER_BIN" ] || err "binary not found at $PIPER_BIN"

# ---- Download voice model ----
download_model_file() {
    local fname="$1"
    local dest="$MODELS_DIR/$fname"
    if [ "${FORCE:-0}" != "1" ] && [ -s "$dest" ]; then
        log "$fname already present (use FORCE=1 to re-download)"
        return
    fi
    local url="https://huggingface.co/$MODEL_REPO/resolve/main/$fname"
    log "downloading $fname ..."
    curl -fL --progress-bar -o "$dest" "$url"
}

download_model_file "$MODEL_FILE"
download_model_file "config.json"

# ---- Install wrapper ----
# stackchan_atama.py pipes plain text via stdin; the native binary expects
# either --text or JSONL stdin. This wrapper reads stdin and forwards as -t.
cat > "$WRAPPER" <<'EOF'
#!/usr/bin/env bash
# Auto-generated by setup_piper.sh — wraps native piper-plus for plain-text stdin input.
set -e
HERE="$(cd "$(dirname "$0")" && pwd)"
BIN="$HERE/../_piper/piper/bin/piper"
TEXT="$(cat)"
exec "$BIN" "$@" -t "$TEXT"
EOF
chmod +x "$WRAPPER"

log "wrapper installed: $WRAPPER"
log ""
log "done. test with:"
log "  echo 'こんにちは' | tools/piper --model models/$MODEL_FILE --config models/config.json -f /tmp/test.wav"
log "  uv run tools/stackchan_atama.py say 'こんにちは'"
