#!/usr/bin/env bash
# Cross-platform setup for piper-plus TTS (default engine for stackchan-atama).
#
# Downloads the piper-plus CLI binary. The 6-language Tsukuyomi-chan model uses
# multilingual phonemes; native piper v1.11 aborts on some multi-codepoint
# phonemes, while piper-plus-cli v1.12 handles this model correctly.
#
# Downloads:
#   - piper-plus CLI from ayutaz/piper-plus releases
#   - tsukuyomi-chan voice model from Hugging Face (ayousanz/piper-plus-tsukuyomi-chan)
# Installs into:
#   <skill>/_piper/    -- CLI binary + ORT runtime
#   <skill>/models/    -- model + config
#   <skill>/tools/piper -- shell wrapper (stdin -> -t conversion)
#
# Usage:
#   tools/setup_piper.sh                  # auto-detect OS/ARCH
#   PIPER_PLUS_VERSION=v1.11.0 tools/setup_piper.sh
#   FORCE=1 tools/setup_piper.sh          # re-download even if installed

set -euo pipefail

PIPER_PLUS_VERSION="${PIPER_PLUS_VERSION:-v1.12.0}"
MODEL_REPO="ayousanz/piper-plus-tsukuyomi-chan"
MODEL_FILE="tsukuyomi-chan-6lang-fp16.onnx"

SKILL_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PIPER_DIR="$SKILL_DIR/_piper"
MODELS_DIR="$SKILL_DIR/models"
WRAPPER="$SKILL_DIR/tools/piper"

log() { printf '[setup_piper] %s\n' "$*"; }
err() { printf '[setup_piper] ERROR: %s\n' "$*" >&2; exit 1; }

# ---- Detect platform ----
OS="$(uname -s)"
ARCH="$(uname -m)"

case "$OS-$ARCH" in
    Darwin-arm64)  ASSET="piper-plus-cli-osx-arm64.tar.gz" ;;
    Linux-aarch64|Linux-arm64)
                   ASSET="piper-plus-cli-linux-arm64.tar.gz" ;;
    Linux-armv7l|Linux-armv6l)
        err "Linux armv7 is not supported by piper-plus-cli. Use VOICEVOX or a supported arm64/x64 machine." ;;
    Linux-x86_64)  ASSET="piper-plus-cli-linux-x64.tar.gz" ;;
    Darwin-x86_64)
                   ASSET="piper-plus-cli-osx-x64.tar.gz" ;;
    *) err "unsupported platform: $OS-$ARCH" ;;
esac

log "platform: $OS-$ARCH -> $ASSET"

# ---- Tools ----
have() { command -v "$1" >/dev/null 2>&1; }
have curl || err "curl is required"
have tar  || err "tar is required"

# ---- Install piper-plus CLI ----
mkdir -p "$PIPER_DIR" "$MODELS_DIR"
PIPER_BIN="$PIPER_DIR/PiperPlus.Cli"

if [ "${FORCE:-0}" = "1" ] || [ ! -x "$PIPER_BIN" ]; then
    log "downloading $ASSET ($PIPER_PLUS_VERSION) ..."
    URL="https://github.com/ayutaz/piper-plus/releases/download/$PIPER_PLUS_VERSION/$ASSET"
    TMP="$(mktemp -d)"
    trap 'rm -rf "$TMP"' EXIT
    curl -fL --progress-bar -o "$TMP/asset.tar.gz" "$URL"
    rm -rf "$PIPER_DIR"
    mkdir -p "$PIPER_DIR"
    tar xzf "$TMP/asset.tar.gz" -C "$PIPER_DIR"
    log "extracted to $PIPER_DIR"

    # Strip macOS quarantine attribute so the binary can run without Gatekeeper prompts
    if [ "$OS" = "Darwin" ] && have xattr; then
        xattr -dr com.apple.quarantine "$PIPER_DIR" 2>/dev/null || true
    fi

    chmod +x "$PIPER_BIN" 2>/dev/null || true
else
    log "piper binary already installed (use FORCE=1 to re-download)"
fi

[ -x "$PIPER_BIN" ] || err "binary not found at $PIPER_BIN"

# ---- Download voice model ----
download_model_file() {
    local fname="$1"
    local dest="$MODELS_DIR/$fname"
    if [ "${FORCE:-0}" != "1" ] && [ -s "$dest" ]; then
        log "$fname already present (use FORCE=1 to re-download)"
        return
    fi
    local url="https://huggingface.co/$MODEL_REPO/resolve/main/$fname"
    log "downloading $fname ..."
    curl -fL --progress-bar -o "$dest" "$url"
}

download_model_file "$MODEL_FILE"
download_model_file "config.json"

# ---- Install wrapper ----
# stackchan_atama.py pipes plain text via stdin. This wrapper reads stdin and
# forwards it as --text so both direct CLI use and Python subprocess use work.
cat > "$WRAPPER" <<'EOF'
#!/usr/bin/env bash
# Auto-generated by setup_piper.sh — wraps piper-plus-cli for plain-text stdin input.
set -e
HERE="$(cd "$(dirname "$0")" && pwd)"
BIN="$HERE/../_piper/PiperPlus.Cli"
TEXT="$(cat)"
# The bundled Tsukuyomi 6-language model card recommends the combined language
# code for automatic language handling, plus length-scale 1.5 for natural speed.
LANGUAGE="${PIPER_LANGUAGE:-ja-en-zh-es-fr-pt}"
LENGTH_SCALE="${PIPER_LENGTH_SCALE:-1.5}"
NOISE_SCALE="${PIPER_NOISE_SCALE:-0.667}"
exec "$BIN" "$@" \
  --language "$LANGUAGE" \
  --length-scale "$LENGTH_SCALE" \
  --noise-scale "$NOISE_SCALE" \
  --quiet -t "$TEXT"
EOF
chmod +x "$WRAPPER"

log "wrapper installed: $WRAPPER"
log ""
log "done. test with:"
log "  echo 'こんにちは' | tools/piper --model models/$MODEL_FILE --config models/config.json -f /tmp/test.wav"
log "  uv run tools/stackchan_atama.py say 'こんにちは'"
